inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 260

Metrics/BlockLength:
  Max: 300

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ClassLength: 
  Max: 150

Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false