inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 260

Metrics/BlockLength:
  Max: 300

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 35

Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false