inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 260

Metrics/BlockLength:
  Max: 300

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 13

Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false