language: ruby

rvm:
  - 2.5.3

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

before_install:
  - gem update --system
  - gem install bundler